# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c958ad33858cdda16ead4735c5cdeec64b947eecb25e6bf9f74374453e26c356dbefa0e554140f8d8f0a82f092a1157be7db35e5fc8bbe94f885abea332de1a2

test:
  secret_key_base: 1948f5229850872572ce1b8fa9dce2332f6b22f434e13379be7a6ada4a77e00a408b45ce2f09476e472459e67de28fc6ed0d54f7ce81973d4ee3c52587ad31e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
